Welcome to <strong><?php echo $alias;?></strong> website. In order to give compliance to which is established in Law 34/2002, of 11 July, about Information Society Services and Electronic Commerce, we proceed to indicate the general information of this website:
<div style="background: #f0f0f0; padding: 20px;"><em>Owner:</em> <?php echo $company;?><br>
<em>CIF/NIF: </em><?php echo $cif;?><br>
<em>Address:</em> <?php echo $address;?><br>
<em>Phone: </em> <?php echo $phone;?><br>
<em>E-mail:</em> <?php echo $email;?><br>
<?php if($books):?><em>Registry Details: </em><?php echo $books;endif;?></div>
&nbsp;

<strong>Terms of use</strong>
The existing conditions regulate the use of the website where information related to <?php echo $alias;?> services is provided. Please read carefully the following information we are providing to you. Accessing this website and using the materials it contains implies that the user has read and accepted, without any reservations, these conditions. This website contains materials such as articles, studies and project descriptions prepared by <?php echo $alias;?>, for informational purposes only. <?php echo $alias;?> informs the user that these materials may be modified, developed or updated at any moment with no prior notification.

<strong>Intellectual and Industrial Property Rights</strong>
The entire content of this website, including as content, but not limited to, documents, text, images, files, photographs, logotypes, graphics, brands, icons, colour combinations, or any other element, its structure and design, the selection and way of presentation of the materials included in it, as well as the software, links and all the audiovisual or sound content, besides the graphic design and source codes needed for its functioning, access and use, are protected by intellectual and industrial property rights, owned by <?php echo $alias;?> or third parties, without it being transferred to any user beyond what is absolutely necessary for ensuring the correct use of the website. In particular, the reproduction, transformation, distribution, public communication, public availability and any other exploitation form, by any manner or form, of the whole or part of this website contents, as well as the design, selection and way of presentation of the materials included is prohibited. This exploitation may only be made by the express authorization of <?php echo $alias;?> provided that <?php echo $alias;?> intellectual and industrial property rights ownership is referred. It shall also be prohibited to decompile, disassemble, reverse engineer, sublicense or transmit in any way, translate or perform acts resulting of the software needed for the functioning, access and use of this website and the services in it offered, as well as perform, with respect to all or part of that software, any of the exploitation acts described in the previous paragraph. The website user shall abstain in any case from deleting, modifying, eluding or amending any protection means or security systems which could be installed in it. The brands, commercial names or distinctive signs are property of <?php echo $alias;?> or third parties, and it may not be construed that Access to the website grants the user any rights over any trademarks, commercial names and or logos or distinctive signs.

<strong>Links</strong>
The links contained in this website may take users to external websites managed by third parties, over which <?php echo $alias;?> has no control, not responding for the contents and status of these sites and webpages, and access to them through this website does not imply that <?php echo $alias;?> recommends or approves its contents.

<strong>Modifications</strong>
In order to improve the website, <?php echo $alias;?> reserves the right, at any moment and without any previous, to modify, expand or suspend temporarily the presentation, configuration, technical specifications and website services, unilaterally. Likewise, <?php echo $alias;?> reserves the right to modify at any moment the present conditions as well as other special conditions.

<strong>Liability Exclusion</strong>
Whoever uses this website does so it his own risk and expense. <?php echo $alias;?>, S.L, their partners, collaborators, employees and representatives assume no responsibility for the errors or omissions that may be found in this website or for any other content that may be accessible from the same. <?php echo $alias;?>, S.L, their partners, collaborators, employees and representatives shall also not be held liable for either any damages arising from the use of this website or any activity undertaken as a result of the information made available herein. The information on this website is provided without any form of guarantee, explicit or implied, and may be changed or updated without prior notice <?php echo $alias;?> does not guarantee the absence of viruses, worms, or in general, any other harmful computer content, which may cause harm or alterations in the informatic system, electronic documents or user files of this website. Consequently, <?php echo $alias;?> does not respond for damages and prejudices caused by such elements to users or third parties. Furthermore, <?php echo $alias;?> assumes no liability or guarantee for the availability and continuity of any access to this web page, or that is free of errors, corresponding to the User, in any case, to have suitable tools to the detection and disinfection of harmful computer content. Users shall be liable for the damages of any nature that <?php echo $alias;?> might suffer as a consequence of breach of any of the obligations to which they are subject in relation with the use of this website pursuant to current legislation. The User is aware of and voluntarily accepts that the use of the Website takes place, in any case, under his/her sole and exclusive responsibility.

<strong id="privacidad">Personal Data Protection</strong>
In accordance with the Organic Law 15/1999, of 13 December, about Personal Data Protection and its development regulations, <?php echo $alias;?> informs you that the personal data you provide to us will be included in an automated file for which <?php echo $alias;?> is responsible. In its website, <?php echo $alias;?> does not request for mandatory data to the users who visit it, thus, the communication of personal data by the user through our website could only take place when they, voluntarily, use the contact section or through the email adresses published in our website. In either of the cases described above, with the fulfillment of this form or sending emails or any other communication to <?php echo $alias;?>, the user gives his/her express consent to the processing of personal details and to receive information on services which we offer, accepting expressly and unequivocally, as well, that the data may be ceded, exclusively with the purposes related above and only to societies directly linked with <?php echo $alias;?>. Under no circumstances <?php echo $alias;?> will use the personal data of the users for purposes which are different from the previously mentioned. Likewise, we communicate that you can exercise your rights to access, modify, amend, cancel and oppose this file through the shipment of a written request by ordinary mail to the following address: <?php echo $alias;?> - <?php echo $address;?> o en la cuenta de correo electónico <?php echo $email;?>.<a name="cookies"></a>

<strong>Cookies Policy</strong>
Like almost all websites, we use cookies in order to facilitate the use of our website. Cookies are small information files which allow us to compare and understand how our users navigate through our website, and thus, to improve the navigation process. You can find out more information about cookies and their use in <a href="http://www.aboutcookies.org" target="_blank">www.aboutcookies.org</a>. The types of cookies that we use are the following:
<ul>
	<li><strong>Own Cookies: </strong>: This website has been developed with a content management application, which uses cookies to facilitate the access and improve the navigation, comment management, functionality, security and overall user experience. For example, the online shop systems use cookies to manage the shopping cart or the orders.</li>
	<li><strong>Social Media Cookies:</strong>: Facebook, Twitter and other social media need to use cookies to recognize the user so they can use their publishing services, for instance, the “Like” button.</li>
	<li><strong>Cookies for Google Analytics: </strong>: The data gathered by the Google Analytics cookies are anonymous and may be only used to evaluate the user experience in our website and to know the detailed statistics about the site visits.</li>
</ul>
<em><strong>By visiting our website, you accept the installation of all those cookies in your device.</strong></em>

Likewise, we inform you about the possibility of configuring your web browser to warn about the cookies reception, which may, if you wish it, prevent them to be installed in your hard disk, or erase them. Listed below are links to different web browsers, through which you could establish that configuration:

<a href="http://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we" target="_blank">Mozilla Firefox</a> | <a href="https://support.google.com/chrome/answer/95647?hl=es" target="_blank">Google Chrome</a> | <a href="http://windows.microsoft.com/es-xl/internet-explorer/delete-manage-cookies#ie=ie-10" target="_blank">Microsoft Internet Explorer</a> | <a href="http://support.apple.com/kb/ph5042" target="_blank">Apple Safari</a> | <a href="http://help.opera.com/Windows/11.50/es-ES/cookies.html" target="_blank">Opera</a>

<strong>
Notice of unlawful or inadequate activities</strong>
In the case that any user of the website has knowledge about links redirecting to sites whose content or services are unlawful, harmful, degrading, violent or contrary to morality may make contact with <?php echo $alias;?> indicating the following data: Personal data of the sender: name, address, phone number and email; description of the situation which reveals the unlawful or inadequate content of the link; in the case of violation of rights, such as intellectual and industrial property, the personal information concerning the owner of the infringed right, when the holder is a person other than the sender. As well, the sender must also provide the instrument which evidences the holder of the violated rights and, if appropriate, his capacity to represent the holder when the latter is not the sender. The reception of the Communication contemplated in this clause by <?php echo $alias;?> will not assume, in accordance with Law 34/2002, 11 July, of Information Society Services and Electronic Commerce, the actual knowledge of the activities and/or contents mentioned by the sender.

<strong>Legislation</strong>
The General Terms of Use and all other legal conditions established in this website shall be governed by Spanish law.