Bienvenido al sitio web de<strong> <?php echo $alias;?></strong> Para dar cumplimiento con lo establecido en la Ley 34/2002, de 11 de julio, de servicios de sociedad de la información y de comercio electrónico, a continuación se indican los datos de información general de este sitio web:
<div style="background: #f0f0f0; padding: 20px;"><em>Titular:</em> <?php echo $company;?><br>
<em>CIF/NIF: </em><?php echo $cif;?><br>
<em>Domicilio:</em> <?php echo $address;?><br>
<em>Teléfono: </em> <?php echo $phone;?><br>
<em>Correo electrónico:</em> <?php echo $email;?><br>
<?php if($books):?><em>Datos Registrales: </em><?php echo $books;endif;?></div>

<strong>Condiciones de Uso</strong>
Las presentes condiciones regulan el uso del sitio web donde se facilita al público información relativa a los servicios de <?php echo $alias;?>. Le rogamos lea detenidamente la información que le facilitamos. El hecho de acceder a este sitio web y utilizar los materiales contenidos en él implica que usted ha leído y acepta, sin reserva alguna, estas condiciones. Este sitio web contiene materiales como artículos, estudios, descripción de proyectos, preparados por <?php echo $alias;?>, con fines únicamente informativos. <?php echo $alias;?>, le informa que estos materiales pueden ser modificados, desarrollados o actualizados en cualquier momento sin notificación previa.

<strong>Derechos de Propiedad Intelectual e Industrial</strong>
La totalidad del contenido de este sitio web, entendiendo por contenido a título meramente enunciativo, textos, imágenes, ficheros, fotografías, logotipos, gráficos, marcas, iconos, combinaciones de colores, o cualquier otro elemento, su estructura y diseño, la selección y forma de presentación de los materiales incluidos en la misma, y el software, links y demás contenidos audiovisuales o sonoros, así como su diseño gráfico y códigos fuentes necesarios para su funcionamiento, acceso y utilización, están protegidos por derechos de propiedad industrial e intelectual, titularidad de <?php echo $alias;?> o de terceros, sin que puedan entenderse cedidos los derechos de explotación sobre los mismos más allá de lo estrictamente necesario para el correcto uso del sitio Web. En particular, quedan prohibidas la reproducción, la transformación, distribución, comunicación pública, puesta a disposición del público y en general cualquier otra forma de explotación, por cualquier procedimiento, de todo o parte de los contenidos de este sitio web, así como de su diseño y la selección y forma de presentación de los materiales incluidos en la misma. Estos actos de explotación sólo podrán ser realizados mediante la autorización expresa de <?php echo $alias;?> y siempre que se haga referencia a la titularidad de <?php echo $alias;?> de los derechos indicados de propiedad intelectual e industrial. Queda asimismo prohibido descompilar, desensamblar, realizar ingeniería inversa, sublicenciar o transmitir de cualquier modo, traducir o realizar obras derivadas de los programas de ordenador necesarios para el funcionamiento, acceso y utilización de este sitio web y los servicios en él contenidos, así como realizar, respecto a todo o parte de tales programas, cualesquiera de los actos de explotación descritos en el párrafo anterior. El usuario del sitio web deberá abstenerse en todo caso de suprimir, alterar, eludir o manipular cualquiera de los dispositivos de protección o sistemas de seguridad que puedan estar instalados en el mismo. Las marcas, nombres comerciales o signos distintivos son titularidad de <?php echo $alias;?> o de terceros, sin que pueda entenderse que el acceso al sitio web atribuya ningún derecho sobre las citadas marcas, nombres comerciales y / o signos distintivos.

<strong>Enlaces</strong>
Los enlaces que contiene este sitio web pueden conducir al usuario a otros sitios y páginas web gestionados por terceros, sobre los que <?php echo $alias;?> no ejerce ningún tipo de control, no responde ni de los contenidos ni del estado de dichos sitios y páginas web, y el acceso a las mismas a través de este sitio web tampoco implica que se recomiende o apruebe sus contenidos.

<strong>Modificaciones</strong>
Con el fin de mejorar el sitio web, <?php echo $alias;?> se reserva el derecho, en cualquier momento y sin previa notificación, a modificar ampliar o suspender temporalmente la presentación, configuración, especificaciones técnicas y servicios del sitio web, de forma unilateral. Asimismo se reserva el derecho de modificar en cualquier momento las presentes condiciones de uso así como otras condiciones particulares.

<strong>Exclusión de responsabilidad</strong>
Quien utiliza este sitio web, lo hace por su propia cuenta y riesgo. <?php echo $alias;?>, sus socios, colaboradores, empleados y representantes no se responsabilizan de los errores u omisiones de los que pudieran adolecer los contenidos este sitio web u otros contenidos a los que se pueda acceder a través de la misma. <?php echo $alias;?>, sus socios, colaboradores, empleados y representantes tampoco podrán ser considerados responsables por los daños derivados de la utilización de este sitio web, ni por cualquier actuación realizada sobre la base de la información que en ella se facilita. La información de este sitio web se proporciona sin garantía de ninguna clase, ni explícita ni implícita, y podrá cambiarse o actualizarse sin previo aviso. <?php echo $alias;?> no garantiza la ausencia de virus, gusanos u otros elementos informáticos lesivos que pudieran causar daños o alteraciones en el sistema informático, los documentos electrónicos o los ficheros del usuario de este sitio web. En consecuencia, <?php echo $alias;?> no responde por los daños y perjuicios que tales elementos pudieran ocasionar al usuario o a terceros. Asimismo no se responsabiliza ni garantiza la disponibilidad y continuidad en el acceso a este sitio web o que el mismo esté libre de errores, correspondiente al usuario del sitio Web, en cualquier caso, la obligación de disponer herramientas adecuadas para la detección y desinfección de programas informáticos dañinos o lesivos. El usuario responderá de los daños y perjuicios de toda naturaleza que <?php echo $alias;?> pueda sufrir como consecuencia del incumplimiento de cualquiera de las obligaciones a que queda sometido por las presentes condiciones. El usuario es consciente y acepta voluntariamente que el uso de cualquier contenido de este sitio web, en todo caso, se hace bajo su única y exclusiva responsabilidad.

<strong id="privacidad">Protección de Datos de Carácter Personal</strong>
En cumplimiento de la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal y su normativa de desarrollo, <?php echo $alias;?> le informa que los datos personales facilitados por usted serán incorporados a un fichero automatizado cuyo responsable y titular es <?php echo $company;?>. En su página web <?php echo $alias;?> no pide obligatoriamente datos a los usuarios que la visiten, por tanto, la comunicación de datos personales por el usuario a través de nuestro sitio web únicamente puede entenderse que tendrá lugar cuando éstos voluntariamente utilicen un formulario de contacto o a través de las direcciones de correo electrónico publicadas en nuestro sitio web. En cualquiera de los casos anteriormente descritos, con la cumplimentación de este formulario o el envío de correos electrónicos u otras comunicaciones a <?php echo $company;?>, el usuario da su consentimiento expreso al tratamiento de sus datos de carácter personal y a recibir comunicaciones sobre los servicios que ofrecemos, aceptando expresa e inequívocamente, asimismo, que puedan ser cedidos sus datos, exclusivamente para las finalidades que se han descrito en el párrafo anterior, a sociedades directamente relacionadas con <?php echo $alias;?>. En ningún caso <?php echo $alias;?> utilizará los datos personales de los usuarios para fines distintos de los anteriormente mencionados. Del mismo modo le comunicamos que puede ejercitar sus derechos de acceso, rectificación, cancelación y oposición al fichero mediante el envío por correo ordinario de la solicitud por escrito a la siguiente dirección: <?php echo $company;?> - <?php echo $address;?> o en la cuenta de correo electónico <?php echo $email;?>.<a name="cookies"></a>


<strong>Política de Cookies</strong>
Al igual que la mayoría de sitios actuales, utilizamos cookies para facilitar el uso de nuestra web. Las cookies son pequeños ficheros de información que nos permiten comparar y entender cómo nuestros usuarios navegan a través de nuestra página web, y de esta manera poder mejorar consecuentemente el proceso de navegación. Puede obtener más información sobre las cookies y su uso en <a href="http://www.aboutcookies.org" target="_blank">www.aboutcookies.org</a>. Los tipos de cookies que utilizamos son:
<ul>
	<li><strong>Cookies propias</strong>: El gestor de contenidos sobre el que funciona esta web utiliza cookies para facilitar el acceso y mejorar la navegación, la gestión de comentarios, la funcionalidad, seguridad y experiencia general del usuario. Por ejemplo, los sistemas de tienda on-line utilizan cookies para gestionar el carrito de la compra o los pedidos.</li>
	<li><strong>Cookies para redes sociales</strong>: Facebook, Twitter y otras redes sociales necesitan utilizar cookies para reconocerle y poder utilizar sus servicios de publicación, como por ejemplo el botón 'me gusta'.</li>
	<li><strong>Cookies para Google Analytics</strong>: Los datos recogidos por las cookies de Google Analytics son anónimos y solo se usan para valorar la experiencia del usuario en nuestra web y conocer la estadística de visitas.</li>
</ul>
<em>Al visitar nuestra página web, acepta la instalación de todas estas cookies en su dispositivo.</em>

Asimismo, le informamos de que tiene la posibilidad de configurar su navegador de modo que se le avise de la recepción de cookies, pudiendo, si así lo desea, impedir que sean instaladas en su disco duro o borrarlas. A continuación le proporcionamos los enlaces de diversos navegadores, a través de los cuales podrá realizar dicha configuración si usted así lo deseara:

<a href="http://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we" target="_blank">Mozilla Firefox</a> | <a href="https://support.google.com/chrome/answer/95647?hl=es" target="_blank">Google Chrome</a> | <a href="http://windows.microsoft.com/es-xl/internet-explorer/delete-manage-cookies#ie=ie-10" target="_blank">Microsoft Internet Explorer</a> | <a href="http://support.apple.com/kb/ph5042" target="_blank">Apple Safari</a> | <a href="http://help.opera.com/Windows/11.50/es-ES/cookies.html" target="_blank">Opera</a>

<strong>
Comunicación de actividades de carácter ilícito e inadecuado</strong>
En caso de que cualquier usuario del sitio web tuviera conocimiento sobre los links que remiten a páginas cuyos contenidos de las cuales o servicios son ilícitos, nocivos, denigrantes, violentos o contrarios a la moral podrá ponerse en contacto con <?php echo $alias;?> indicando los siguientes datos: Datos personales del comunicante: nombre, dirección, número de teléfono y dirección electrónica; Descripción de los hechos que revelan el carácter ilícito o inadecuado del hiperenlace; en el supuesto de violación de derechos, tales como la propiedad intelectual e industrial, los datos personales del titular del derecho infringido, cuando sea persona distinta del comunicante. Asimismo, deberá aportar el título que acredite la legitimación del titular de los derechos y, en su caso, el de representación para actuar por cuenta del titular cuando sea persona distinta del comunicante; La recepción por parte de <?php echo $alias;?> de la comunicación prevista en esta cláusula no supondrá, según lo dispuesto en la Ley 34/2002 de 11 de julio, de servicios de sociedad de la información y de comercio electrónico, el conocimiento efectivo de las actividades y / o contenidos indicados por el comunicante.

<strong>Legislación</strong>
Las presentes condiciones de uso se rigen en todos y cada uno de sus extremos por la legislación española.